//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace titov_zotov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Titov_ZotovEntities : DbContext
    {
        private static Titov_ZotovEntities _context;
        public Titov_ZotovEntities()
            : base("name=Titov_ZotovEntities")
        {
        }
        public static Titov_ZotovEntities GetContext()
        {
            if (_context == null)
                _context = new Titov_ZotovEntities();
            return _context; }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
    }
}
